### PR TITLE
Fix container query in banners

### LINKED ISSUE #318: Fix container query in `banners`
**Provide the exact quote of the error or issue:**

We should modify the `_container` query to use breakpoints provided by `@yamada-ui/react`.

`contents\data-display\banners\cookie\index.tsx`

This issue will be automatically unassigned after two weeks have passed since it was assigned. Once unassigned, it may be picked up by someone else for work.

### PR DESCRIPTION
**Pull request by hinataOhyama**
Closes #318  

## Description

delete `_container` .
Verified that the current state is the same as it was before the modification.

### CODE REVIEW

File: contents/data-display/banners/cookie/index.tsx [hunk 1]
```diff
@@ -16,24 +16,14 @@ const Banner: FC = () => {
     <Card variant="outline" maxW="md" shadow="sm">
       <CardBody>
         <Grid
-          templateAreas={`
+          templateAreas={{
+            base: `
```
Comment (illionillion) [inline contents/data-display/banners/cookie/index.tsx:20]: I thought you don't need`base` because it doesn't resize to fit the screen width.

```suggestion
          templateAreas={`
```

File: contents/data-display/banners/cookie/index.tsx [hunk 2]
```diff
@@ -16,24 +16,14 @@ const Banner: FC = () => {
...
             "title title close"
             "content content content"
             "empty button button"
-          `}
+          `,
+          }}
```
Comment (illionillion) [inline contents/data-display/banners/cookie/index.tsx:25]:
```suggestion
          `}
```

File: contents/data-display/banners/cookie/index.tsx (hunk 1 above)
Comment (oyama-hinata) [reply contents/data-display/banners/cookie/index.tsx:20]: As you said.
It is my mistake.
Thanks for reviewing it.

Comment (hinataOhyama) [reply contents/data-display/banners/cookie/index.tsx:20]: As you said.
It is my mistake.
Thanks for reviewing it.

File: contents/data-display/banners/cookie/index.tsx [hunk 3]
```diff
@@ -46,7 +33,9 @@ const Banner: FC = () => {
               dangerouslySetInnerHTML={{
                 __html: `<p>This website uses cookies to enhance user experience and to improve the website. By clicking "Accept all", you consent to the use of cookies. For more details, please refer to our Privacy Policy.</p>`,
               }}
-              onClick={(e) => e.preventDefault()}
+              onClick={(e: React.MouseEvent<HTMLElement, MouseEvent>) =>
```
Comment (illionillion) [inline contents/data-display/banners/cookie/index.tsx:36]: What is the reason for specifying the type here?
I don't think it is necessary because the type is specified by default.

Comment (hinataOhyama) [reply contents/data-display/banners/cookie/index.tsx:36]: I thought it was basically better to specify types explicitly, but is it better not to write default types, etc. explicitly?

Comment (taroj1205) [reply contents/data-display/banners/cookie/index.tsx]: @illionillion I have taken over the PR and fixed the issues. Please review again.

**Review by illionillion — APPROVED** [review]

File: contents/data-display/banners/cookie/index.tsx (hunk 3 above)
Comment (illionillion) [reply contents/data-display/banners/cookie/index.tsx]: @hinataOhyama @taroj1205 

Sorry for the delay.
I checked.

**Review by hirotomoyamada — APPROVED** [review]
