### PR TITLE
fix(pagination): resolve nested button issue in pagination component

### LINKED ISSUE #516: Fix Simple pagination button
### Subject

Fix Simple pagination button

### Description

Fix nested buttons.
image

### Are you willing to participate in the development of this component and create a pull request?

None

### PR DESCRIPTION
**Pull request by RudhraBharathy**
Closes #516 

## Description

Fixes the issue of nested buttons in the pagination component by refactoring the button rendering logic. The `controlPrevProps` and `controlNextProps` were updated to remove the nesting and ensure styling consistency.

## Current behavior (updates)

The `Pagination` component currently renders buttons with nested button elements, which is semantically incorrect and causes issues with the UI.

## New behavior

The pagination buttons now render with text only (e.g., "Prev" and "Next"), and all styling is applied directly to the buttons themselves. This removes the nested button structure and ensures that the buttons are styled correctly while maintaining the same appearance.

## Is this a breaking change (Yes/No):

No

## Additional Information

None

### CODE REVIEW

File: contents/navigation/paginations/simple-button/index.tsx [hunk 1]
```diff
@@ -1,9 +1,16 @@
-import { Box, Button, Pagination, Text, ui } from "@yamada-ui/react"
+import { Box, Pagination, Text, ui } from "@yamada-ui/react"
 import { useState, type FC } from "react"
 
 const SimpleButton: FC = () => {
   const [page, onChange] = useState<number>(1)
 
+  const buttonStyles = {
```
Comment (illionillion) [inline contents/navigation/paginations/simple-button/index.tsx:7]: I want you to put a mold on it.

```suggestion
  const buttonStyles:HTMLUIProps<"button"> = {
```

**Review by illionillion — COMMENTED** [review]
@RudhraBharathy Thanks for PR!!

File: contents/navigation/paginations/simple-button/index.tsx (hunk 1 above)
Comment (RudhraBharathy) [reply contents/navigation/paginations/simple-button/index.tsx:7]: Sure!!

**Comment by RudhraBharathy** [comment]
Hi @illionillion 

I've made the requested change to update the buttonStyles type to HTMLUIProps<"button">. Please let me know if everything looks good now, or if there's anything else you'd like me to address!

**Review by neginasu — APPROVED** [review]
PR confirmed!
LGTM🎉

**Review by illionillion — APPROVED** [review]
@RudhraBharathy 
Thanks

**Review by hirotomoyamada — APPROVED** [review]
