### PR TITLE
fix: changed `size` to `boxSize`

### LINKED ISSUE #407: Change `size` of `Loading` component to `boxSize`
### Provide the exact quote of the error or issue

Modify the relevant part in `component-preview.tsx`

### Does the feature already exist? Please link to it.

_No response_

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### PR DESCRIPTION
**Pull request by illionillion**
Closes #407  

## Description

`size` has been deprecated and has been modified.

### CODE REVIEW

**Review by taroj1205 — APPROVED** [review]
LGTM

File: components/data-display/component-preview.tsx [hunk 1]
```diff
@@ -186,7 +186,7 @@ export const ComponentPreview = memo(
                         </Box>
                       ) : (
                         <Center boxSize="full" flex="1">
-                          <Loading size="6xl" {...loadingProps} />
+                          <Loading boxSize="6xl" {...loadingProps} />
                         </Center>
```
Comment (odendayoko) [inline components/data-display/component-preview.tsx:190]: @illionillion 
Please use fontSize instead of boxSize

File: components/data-display/component-preview.tsx [hunk 2]
```diff
@@ -211,7 +211,7 @@ export const ComponentPreview = memo(
               </Box>
             ) : (
               <Center boxSize="full" flex="1">
-                <Loading size="6xl" {...loadingProps} />
+                <Loading boxSize="6xl" {...loadingProps} />
```
Comment (odendayoko) [inline components/data-display/component-preview.tsx:214]: @illionillion 
Please do the same here.

**Review by odendayoko — DISMISSED** [review]

File: components/data-display/component-preview.tsx (hunk 1 above)
Comment (illionillion) [reply components/data-display/component-preview.tsx:190]: Why?

**Comment by illionillion** [comment]
Thanks for review.
I fixed it.
Please review again.

**Review by taroj1205 — APPROVED** [review]
LGTM Thanks!

I think you should change the PR title though.

**Review by hirotomoyamada — APPROVED** [review]
